#!/usr/bin/env python3
"""gen_fixtures.py — embed the Go golden snapshot JSON as C string literals.

Reads testdata/snapshots/example.json and example_full.json from the repo root
and writes firmware/test/host/fixtures/fixtures.h with raw-string literals.
Run after any golden regeneration:

    python3 firmware/scripts/gen_fixtures.py
"""
import json
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
# The Go golden files live in two testdata trees; search both.
GOLDEN_DIRS = [
    os.path.join(REPO_ROOT, "testdata", "snapshots"),
    os.path.join(REPO_ROOT, "internal", "snapshot", "testdata", "snapshots"),
]
OUT_DIR = os.path.join(REPO_ROOT, "firmware", "test", "host", "fixtures")
OUT_FILE = os.path.join(OUT_DIR, "fixtures.h")

# (go_filename, c_variable, human_name)
FIXTURES = [
    ("example.json", "kSnapshotExample", "example"),
    ("example_full.json", "kSnapshotExampleFull", "example_full"),
]

HEADER = """\
// firmware/test/host/fixtures/fixtures.h — AUTO-GENERATED by scripts/gen_fixtures.py.
// DO NOT EDIT BY HAND; re-run `python3 firmware/scripts/gen_fixtures.py`.
#pragma once

"""


def find_golden(fname):
    for d in GOLDEN_DIRS:
        p = os.path.join(d, fname)
        if os.path.isfile(p):
            return p
    return None


def main() -> int:
    os.makedirs(OUT_DIR, exist_ok=True)
    parts = [HEADER]
    for fname, var, name in FIXTURES:
        src = find_golden(fname)
        if src is None:
            print(f"error: {fname} not found in {GOLDEN_DIRS}", file=sys.stderr)
            return 1
        with open(src, "r", encoding="utf-8") as f:
            raw = f.read()
        # Validate JSON, then re-serialize compact for a stable raw string.
        data = json.loads(raw)
        compact = json.dumps(data, separators=(",", ":"))
        parts.append(f'static const char* {var} = R"json(\n{compact}\n)json";\n\n')
    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write("".join(parts))
    print(f"Generated {OUT_FILE} ({len(FIXTURES)} fixtures)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
