#!/usr/bin/env bash
# sync-prices.sh — regenerate internal/stats/prices.go from models.dev/api.json.
#
# Usage: make sync-prices  (or: bash scripts/sync-prices.sh)
#
# Downloads the authoritative model pricing table from models.dev and writes
# a new prices.go with the fetched source URL + date in a comment. The
# generator is a Python script (stdlib json+urllib only); the runtime binary
# stays dependency-free. After running, review and commit prices.go.
set -euo pipefail

cd "$(dirname "$0")/.."

URL="https://models.dev/api.json"
OUT="internal/stats/prices.go"
PY="$(command -v python3 || command -v python)"

if [ -z "$PY" ]; then
    echo "error: python3 not found" >&2
    exit 1
fi

echo "fetching $URL ..."

"$PY" - "$URL" "$OUT" <<'PYEOF'
import json, sys, urllib.request, datetime

url, out = sys.argv[1], sys.argv[2]
today = datetime.date.today().isoformat()

req = urllib.request.Request(url, headers={"User-Agent": "usaged-price-sync"})
with urllib.request.urlopen(req, timeout=30) as resp:
    data = json.load(resp)

# models.dev/api.json structure:
#   {"models": [{"id": "...", "pricing": {"prompt": X, "completion": Y, "image": ..., ...}}]}
# OpenAI models have ids like "openai/gpt-4.1", "openai/o1", "openai/o3-mini", etc.
# We keep the canonical vendor-prefixed id (do NOT strip "openai/") per ORDER #40/CORRECTION.
# fugu-* models may appear as "openai/fugu-ultra" or bare "fugu-ultra"; both are kept.

def per_million(rate):
    """models.dev rates are per-token; convert to per-1M-token USD."""
    return round(rate * 1e6, 4)

rows = {}
for m in data.get("models", []):
    mid = m.get("id", "")
    pricing = m.get("pricing", {})
    if not pricing:
        continue
    # Only OpenAI-family models (prefix "openai/gpt-" or "openai/o" or "openai/fugu")
    if not (mid.startswith("openai/gpt-") or mid.startswith("openai/o") or mid.startswith("openai/fugu")):
        continue
    # Keep canonical prefix; strip nothing.
    name = mid
    inp = per_million(pricing.get("prompt", 0))
    outp = per_million(pricing.get("completion", 0))
    cache_read = per_million(pricing.get("cache_read", 0)) if pricing.get("cache_read") else 0
    cache_write = per_million(pricing.get("cache_write", 0)) if pricing.get("cache_write") else 0
    rows[name] = (inp, outp, cache_read, cache_write)

# Build the Go source.
lines = []
lines.append('// Code generated by scripts/sync-prices.sh from %s on %s.' % (url, today))
lines.append('// DO NOT EDIT — regenerate with `make sync-prices`.')
lines.append('')
lines.append('package stats')
lines.append('')
lines.append('// Price is the per-1M-token cost in USD for a model.')
lines.append('type Price struct {')
lines.append('\tInput      float64 `json:"input"`')
lines.append('\tOutput     float64 `json:"output"`')
lines.append('\tCacheRead  float64 `json:"cache_read"`')
lines.append('\tCacheWrite float64 `json:"cache_write"`')
lines.append('}')
lines.append('')
lines.append('// Cost multiplies a token count by the per-1M rate.')
lines.append('func (p Price) Cost(t Tokens) float64 {')
lines.append('\treturn (float64(t.Input)*p.Input +')
lines.append('\t\tfloat64(t.Output)*p.Output +')
lines.append('\t\tfloat64(t.CacheRead)*p.CacheRead +')
lines.append('\t\tfloat64(t.CacheWrite)*p.CacheWrite) / 1e6')
lines.append('}')
lines.append('')
lines.append('// prices maps model identifiers to their per-1M-token USD rates.')
lines.append('// OpenAI/Codex rates from %s (fetched %s), using canonical openai/* names.' % (url, today))
lines.append('// cache_write is read from models.dev per model — gpt-5.6-sol publishes 5,')
lines.append('// gpt-5.5 has no cache_write published (Codex does not bill cache creation).')
lines.append('var prices = map[string]Price{')

for name in sorted(rows):
    inp, outp, cr, cw = rows[name]
    lines.append('\t"%s": {%s, %s, %s, %s},' % (name, f(inp), f(outp), f(cr), f(cw)))

lines.append('\t"qwen/qwen-3-32b":          {0.2, 0.6, 0, 0},')
lines.append('\t"meta-llama/llama-4-scout": {0.18, 0.55, 0, 0},')
lines.append('}')

with open(out, 'w') as f:
    f.write('\n'.join(lines) + '\n')

print("wrote %s (%d OpenAI models)" % (out, len(rows)))
PYEOF

echo "done. Review and commit $OUT."
